- hosts: webservers



  tasks:



    - name: copying file with playbook

      become: true

      copy:

        src: ~/ansible/workspace/myproject/target/SpringBootMavenWebApp-0.0.2-SNAPSHOT.war

        dest: /var/www/html/
