
---

- hosts: jenkinsserver

  tasks:

    - name: Git checkout

      git:

        repo: 'https://github.com/altafs1/SpringBootMavenWebApp.git'

        dest: ~/ansible/workspace/myproject/

    - name: maven clean package

      command: mvn -f ~/ansible/workspace/myproject/pom.xml clean package

    - name: copy war file

      command: cp -f ~/ansible/workspace/myproject/target/SpringBootMavenWebApp-0.0.2-SNAPSHOT.war /tmp/
